param(
    [string]$Source = "docs/gui-testability-analyzer-requirements.md",
    [string]$Output = "knowledge/requirements/rq-index.generated.md",
    [switch]$Quiet
)

$ErrorActionPreference = "Stop"

$sourcePath = (Resolve-Path -LiteralPath $Source).Path
$sourceFileName = Split-Path -Leaf $sourcePath
$sourceMarkdownPath = "../../docs/$sourceFileName"
if ([System.IO.Path]::IsPathRooted($Output)) {
    $outputPath = $Output
} else {
    $outputPath = Join-Path (Get-Location) $Output
}
$outputDir = Split-Path -Parent $outputPath
if (-not (Test-Path -LiteralPath $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir | Out-Null
}

$headingPattern = [regex]"^### (RQ-\d{3}):\s*(.+)$"
$sourceLines = @(Get-Content -LiteralPath $sourcePath -Encoding UTF8)
$rqHeadings = New-Object System.Collections.Generic.List[object]

for ($i = 0; $i -lt $sourceLines.Count; $i++) {
    $headingMatch = $headingPattern.Match($sourceLines[$i])
    if (-not $headingMatch.Success) {
        continue
    }

    $rqHeadings.Add([pscustomobject]@{
        Rq = $headingMatch.Groups[1].Value
        Title = $headingMatch.Groups[2].Value.Trim()
        LineNumber = $i + 1
    }) | Out-Null
}
$timestamp = $null
if (Test-Path -LiteralPath $outputPath -PathType Leaf) {
    $existingTimestampLine = Get-Content -LiteralPath $outputPath -Encoding UTF8 |
        Where-Object { $_ -match "^\s*timestamp\s*:\s*(.+?)\s*$" } |
        Select-Object -First 1
    if ($existingTimestampLine) {
        $timestamp = ($existingTimestampLine -replace "^\s*timestamp\s*:\s*", "").Trim()
    }
}

if ([string]::IsNullOrWhiteSpace($timestamp)) {
    $timestamp = Get-Date -Format "yyyy-MM-ddTHH:mm:ssK"
}

$lines = @(
    "---",
    "type: Requirement Index",
    "title: Surveyor RQ Index",
    "description: Generated index of RQ headings from the canonical requirement specification.",
    "resource: $sourceMarkdownPath",
    "tags: [requirements, generated, traceability]",
    "timestamp: $timestamp",
    "---",
    "",
    "# Surveyor RQ Index",
    "",
    "Generated from [$sourceFileName]($sourceMarkdownPath).",
    "",
    "| RQ | Title | Source Line |",
    "| -- | -- | -- |"
)

foreach ($heading in $rqHeadings) {
    $rq = $heading.Rq
    $title = $heading.Title
    $lineNumber = $heading.LineNumber
    $sourceLink = "$sourceMarkdownPath#L$lineNumber"
    $lines += "| " + '`' + $rq + '`' + " | $title | [L$lineNumber]($sourceLink) |"
}

$lines += ""
$lines += "# Notes"
$lines += ""
$lines += 'This file is generated by `tools/requirements/Export-RqIndex.ps1`. Do not edit generated rows by hand.'

$utf8NoBom = New-Object System.Text.UTF8Encoding -ArgumentList $false
[System.IO.File]::WriteAllLines($outputPath, $lines, $utf8NoBom)
if (-not $Quiet) {
    Write-Host "Exported $($rqHeadings.Count) requirements to $Output."
}
