param(
    [string]$Source = "docs/gui-testability-analyzer-requirements.md",
    [string]$Output = "knowledge/requirements/rq-index.generated.md"
)

$ErrorActionPreference = "Stop"

$sourcePath = Resolve-Path -LiteralPath $Source
$sourceFileName = Split-Path -Leaf $sourcePath
$sourceMarkdownPath = "../../docs/$sourceFileName"
$outputPath = Join-Path (Get-Location) $Output
$outputDir = Split-Path -Parent $outputPath
if (-not (Test-Path -LiteralPath $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir | Out-Null
}

$matches = Select-String -LiteralPath $sourcePath -Encoding UTF8 -Pattern "^### (RQ-\d{3}):\s*(.+)$"
$timestamp = Get-Date -Format "yyyy-MM-ddTHH:mm:ssK"

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("---")
$lines.Add("type: Requirement Index")
$lines.Add("title: Surveyor RQ Index")
$lines.Add("description: Generated index of RQ headings from the canonical requirement specification.")
$lines.Add("resource: $sourceMarkdownPath")
$lines.Add("tags: [requirements, generated, traceability]")
$lines.Add("timestamp: $timestamp")
$lines.Add("---")
$lines.Add("")
$lines.Add("# Surveyor RQ Index")
$lines.Add("")
$lines.Add("Generated from [$sourceFileName]($sourceMarkdownPath).")
$lines.Add("")
$lines.Add("| RQ | Title | Source Line |")
$lines.Add("| -- | -- | -- |")

foreach ($match in $matches) {
    $rq = $match.Matches[0].Groups[1].Value
    $title = $match.Matches[0].Groups[2].Value.Trim()
    $lineNumber = $match.LineNumber
    $sourceLink = "$sourceMarkdownPath#L$lineNumber"
    $lines.Add("| " + '`' + $rq + '`' + " | $title | [L$lineNumber]($sourceLink) |")
}

$lines.Add("")
$lines.Add("# Notes")
$lines.Add("")
$lines.Add('This file is generated by `tools/requirements/Export-RqIndex.ps1`. Do not edit generated rows by hand.')

Set-Content -LiteralPath $outputPath -Value $lines -Encoding UTF8
Write-Host "Exported $($matches.Count) requirements to $Output."
