<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Surveyor.Adapters.Uia</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Surveyor.Adapters.Discovery\Surveyor.Adapters.Discovery.csproj" />
    <ProjectReference Include="..\Surveyor.Adapters.Uia.Audit\Surveyor.Adapters.Uia.Audit.csproj" />
    <ProjectReference Include="..\Surveyor.Application\Surveyor.Application.csproj" />
    <ProjectReference Include="..\Surveyor.Domain\Surveyor.Domain.csproj" />
  </ItemGroup>
</Project>
